name: Python CI

on:
  push:
    branches: # Only run on pushes to these branches
      - main
      # Add other branches like 'develop' if needed
    # Explicitly ignore tags for the push trigger
    tags-ignore:
      - "v*.*.*"
  pull_request: # Run on pull requests targeting these branches
    branches:
      - main

permissions:
  contents: read # Default permission

jobs:
  test:
    runs-on: ${{ matrix.os }} # Run on different OS
    strategy:
      fail-fast: false # Don't cancel all jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"] # Only test Python 3.10 and newer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # List the contents of the current directory
          python -c "import os; print(os.listdir('.'))"
          # Install in development mode to ensure the package is discoverable
          pip install -e .[dev]
          # Display installed packages for debugging
          pip list

      - name: Show directory structure
        shell: bash
        run: |
          # Use find for all platforms with bash shell
          find . -type f -name "*.py" | grep -v "__pycache__" | sort

      - name: Run tests with Python path
        run: |
          # Explicitly set PYTHONPATH to include the current directory
          $env:PYTHONPATH = ".;$env:PYTHONPATH"
          python -m pytest
        shell: pwsh
        if: runner.os == 'Windows'

      - name: Run tests on Unix
        run: |
          # Set PYTHONPATH on Unix systems
          export PYTHONPATH=.:$PYTHONPATH
          python -m pytest
        shell: bash
        if: runner.os != 'Windows'

  lint-format:
    runs-on: ubuntu-latest
    needs: test # Optional: Run only if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Use a recent version for linting

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] # Need black, ruff, etc. from dev dependencies

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Lint with Ruff
        run: |
          ruff check .
