name: Python CI

on:
  push:
    branches: # Only run on pushes to these branches
      - main
      # Add other branches like 'develop' if needed
    # Explicitly ignore tags for the push trigger
    tags-ignore:
      - "v*.*.*"
  pull_request: # Run on pull requests targeting these branches
    branches:
      - main

permissions:
  contents: read # Default permission

jobs:
  test:
    runs-on: ${{ matrix.os }} # Run on different OS
    strategy:
      fail-fast: false # Don't cancel all jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"] # Only test Python 3.10 and newer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        shell: bash
        run: |
          echo "Workspace directory content:"
          find . -type d -maxdepth 2
          echo "Python files:"
          find . -name "*.py" | head -20

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Handle case-sensitivity issues on Ubuntu
      - name: Ensure package directory exists with correct name (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          if [ -d "PromptPrep" ] && [ ! -d "promptprep" ]; then
            cp -r PromptPrep promptprep
          fi

      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-mock

      - name: Install the package and its dependencies
        run: |
          # Install the package without the dev dependencies first
          pip install -e .

      - name: Run tests with pytest
        run: |
          # Set PYTHONPATH to include current directory
          python -m pytest tests/

  lint-format:
    runs-on: ubuntu-latest
    needs: test # Run only if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Use a recent version for linting

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Lint with Ruff
        run: |
          ruff check .
