name: Publish Python Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Trigger on tags like v0.1.0, v1.2.3

permissions:
  contents: read
  # IMPORTANT: This permission is required for pypa/gh-action-pypi-publish
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use a recent stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build # Need build tool

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No API token needed here! It uses OIDC (trusted publisher)
        # You need to configure PyPI for trusted publishing first.
        # See: https://docs.pypi.org/trusted-publishers/

    # Optional: Publish to TestPyPI as well (or instead during testing)
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     repository-url: https://test.pypi.org/legacy/
