name: Publish Python Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Trigger on tags like v0.1.0, v1.2.3

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Use Python 3.10 to match minimum required version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build # Need build tool

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # You need to create a PyPI API token and add it as a GitHub secret
          # See: https://pypi.org/help/#apitoken

    # Optional: Publish to TestPyPI as well (or instead during testing)
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     repository-url: https://test.pypi.org/legacy/
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
